FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["Covol/Covol.csproj", "Covol/"]
RUN dotnet restore "Covol/Covol.csproj"
COPY . .
WORKDIR "/src/Covol"
RUN dotnet build "Covol.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Covol.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Covol.dll"]